version: "3.8"
services:
        environment:
                container_name: environment
                image: environment:latest
                hostname: environment

                volumes:
                        - ~/project:/root/project

                # Ensure the image doens't close right after startup
                command: /bin/bash
                stdin_open: true        # docker run -i
                tty: true               # docker run -t
                
                deploy:               
                        restart_policy:
                               condition: always

        mosquitto:
                container_name: mosquitto
                image: eclipse-mosquitto:latest
                hostname: mosquitto
                
                expose:
                        - 1883
                        - 9001
                ports:
                        - "1883:1883"
                        - "9001:9001"
                volumes:
                        - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
                
                deploy:
                        restart_policy:
                               condition: always

