#!/usr/bin/bash

OUTPUT=~/.bash_aliases

if [ ! -d .generated ]; then
	mkdir .generated
fi

echo "##### Generated by setup.py ######" 	>  .generated/.bash_aliases
echo "SETUP_DIR=$PWD" 				>> .generated/.bash_aliases
echo ""		 				>> .generated/.bash_aliases

cat script/aliases 				>> .generated/.bash_aliases

cp .generated/.bash_aliases $OUTPUT

echo "development shortcuts added in $OUTPUT"
